---
title: "Sentiment Analysis"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}

library(flexdashboard)
library(tm)
library(SnowballC)
library(ggplot2)
library(ggthemes)
library(syuzhet)
library(tidyverse)
library(shiny)
library(rsconnect)
```

```{r, include=FALSE}
source("Sentiment Analysis.R", local = knitr::knit_global())
```



Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
sliderInput("n", 
            "Select number of emotions/words to display:",
            1,
            nrow(tdm_d),
            value = 5,
            step = 1,
            max = 20
            )

```

Column 
-------------------------------------

### Most Popular Emotions

```{r}
renderPlot({
nrcs2_filtered = head(nrcs2[order(-nrcs2$percent),], input$n)

ggplot(nrcs2_filtered, aes(x = reorder(emotion, percent), y = percent, fill = emotion, label = scales::percent(percent))) +
  geom_bar(stat = "identity") +
  xlab("Emotion") + 
  ylab("Frequency") +
  scale_y_continuous(labels = scales::percent) +
  geom_text(nudge_y= .007,
            color="black",
            size = 5,
            fontface="bold",
            )+
  theme_minimal() +
  
  coord_flip()
})

```

### Top Words in Reviews

```{r}
renderPlot({
tdm_d_filtered = head(tdm_d[order(-tdm_d$freq),], input$n)
  
ggplot(tdm_d_filtered, aes(x = reorder(word, -freq), y = freq, fill = word,
                        label = freq)) +
  geom_bar(stat = "identity") +
  xlab("Words") + 
  ylab("Frequency") +
  geom_text(vjust = -0.2,
            color="black",
            size = 5,
            fontface="bold",
  )+
  theme_minimal()
})
```

### Percentage of Positive and Negative Reviews

```{r}
renderPlot({
 nrcs[9:10,] %>% 
ggplot(aes(x = reorder(sentiment, -frequency), y = percent, 
           fill = sentiment, label = scales::percent(percent))) +
  geom_bar(stat = "identity") +
  xlab("Sentiments") + 
  ylab("Frequency") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,0.3)) +
  geom_text(nudge_y= .007,
            color="black",
            size = 5,
            fontface="bold",
  )+
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_minimal()
})
```


